### ISSUE TITLE
Typescript definitions

### ISSUE THREAD

**Issue by Banhawy** [MichalSzorad/react-social-login-buttons#12]
This is a great module for social login and custom buttons. Is there any plans to support Typescript in the future? Maybe there is a separate project for that I am not aware of?

**Comment by MichalSzorad** [comment]
Hi @Banhawy, I will definitely add types soon! I had this idea a few days ago and would like to work on that the next weekend.

Thanks for the question!

**Comment by Banhawy** [comment]
Thanks for the answer @MichalSzorad! I was thinking of contributing but I have not yet written a TS definition before. Nevertheless, I will give it a shot this week and if it works for me I'll do a pull request.

Cheers

**Comment by MichalSzorad** [comment]
Hi @Banhawy, what do you think about #13? It works great for me.

**Comment by Banhawy** [comment]
Works like a charm!
