### ISSUE TITLE
createButton can't be used in TypeScript

### ISSUE THREAD

**Issue by tomasklima** [MichalSzorad/react-social-login-buttons#16]
Hello @MichalSzorad,

one more thing to fix in types is needed: add declaration for createButton function. If I try to import it this error is occured:

```
Could not find a declaration file for module 'react-social-login-buttons/lib/buttons/create-button'. '/Users/darbic/work-live/dev/aiteq-specialists/node_modules/react-social-login-buttons/lib/buttons/create-button.js' implicitly has an 'any' type.
Try `npm install @types/react-social-login-buttons` if it exists or add a new declaration (.d.ts) file containing `declare module 'react-social-login-buttons';`
```
Thanks.

Tomas

**Comment by MichalSzorad** [comment]
Hi @tomasklima, thank you for the issue. I will take a look at this as soon as I can.

**Comment by MichalSzorad** [comment]
The new version should be available on npm. 

Please note, that this utils is now imported like this
`import {createButton} from "react-social-login-buttons";`
