### ISSUE TITLE
Can't use custom icon from font awesome

### ISSUE THREAD

**Issue by dumblole** [MichalSzorad/react-social-login-buttons#19]
```javascript
import React from "react";
import { createButton } from "react-social-login-buttons";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import { faSignOutAlt } from "@fortawesome/free-solid-svg-icons";
import { createSvgIcon } from "react-social-login-buttons";

const Icon = props => <FontAwesomeIcon icon={faSignOutAlt} />;
const config = {
  text: "Logout",
  icon: Icon,
  iconFormat: name => `fa fa-${name}`,
  style: { background: "#3b5998" },
  activeStyle: { background: "#293e69" }
};
/** My Facebook login button. */
const LogOut = createButton(config);

export default LogOut;
```
Am I doing something wrong here?
I am passing in a component

**Comment by MichalSzorad** [comment]
Hi there!

Thank you for the feedback. I have tried to run your example and it looks like it works just fine. Take a look  https://codesandbox.io/s/z6o3y79j63

Could you provide more details, please?

**Comment by dumblole** [comment]
Thank you very much!
I'm not sure what I've been doing wrong yesterday - I was pretty frustrated.

I got it working now after looking over what you've written (Even though there was practically no difference).

I really appreciate the fast response.
