### ISSUE TITLE
Custom SVG icon not working

### ISSUE THREAD

**Issue by junaidatique** [MichalSzorad/react-social-login-buttons#20]
Hi

I am trying to include following SVG icon, but it is not working.

https://github.com/bufferapp/buffer-blog-v2/blob/master/wp-content/themes/buffer-v2/images/buffer-logomark.svg?short_path=ad18f60

my code is 
```javascript
import React from "react";
import { createButton, createSvgIcon } from "react-social-login-buttons";
import BufferIcon from "./icons/buffer.svg";

const icon = createSvgIcon(BufferIcon);

const config = {
  text: "Connect Instagram, LinkedIn",
  icon: icon,
  // iconFormat: name => `fa fa-${name}`,
  style: { background: "#CED7DF" },
  activeStyle: { background: "#293e69" }
};

export default createButton(config);
```

I am getting following error.

`TypeError: Object(...) is not a function`
 
on this line

`const icon = createSvgIcon(BufferIcon);`

Please help. 

Thanks.

**Comment by MichalSzorad** [comment]
Hi @junaidatique, 

thanks for caring! I will take a look at this later today.

**Comment by junaidatique** [comment]
I have created a pull request to fix this issue.
