### ISSUE TITLE
Can it work with styled-components?

### ISSUE THREAD

**Issue by cuttlas** [MichalSzorad/react-social-login-buttons#23]
Hi. Is there a way to style the buttons using styled-components library?

I'm trying the following, but it doesn't seem to work:

```javascript
import styled from "styled-components";
import {
  FacebookLoginButton,
} from "react-social-login-buttons";

export const FacebookButton = styled(FacebookLoginButton)`
  width: 150px;
`;
```

Thanks.

**Comment by MichalSzorad** [comment]
Hi @cuttlas,

thanks for submitting the issue! I will take a closer look at this issue later today.

**Comment by MichalSzorad** [comment]
@cuttlas Check the version 2.3.0. It should be working now. Thanks!

**Comment by cuttlas** [comment]
After more testing, I have found a problem. It works great for setting styles that the component doesn't have, but it cannot override styles that the component already has. I guess the inline styles always take precedence over the styled-components class.

For example, here the width is correctly set, but the font-size remains the same:
```javascript
export const FacebookButton = styled(FacebookLoginButton)`
  width: 200px;
  font-size: 15px;
`;
```
I'm afraid there's no easy fix for this.

**Comment by MichalSzorad** [comment]
@cuttlas Have you tried putting a styled span inside the FacebookLoginButton? Eg
```jsx
<FacebookLoginButton>
        <SpanWithSmallFont>Login with facebook</SpanWithSmallFont>
</FacebookLoginButton>
```

**Comment by cuttlas** [comment]
Hey, sorry for the late response. Your solution works perfectly, thanks!
