### ISSUE TITLE
Facebook login doesn't work when in ios webview

### ISSUE THREAD

**Issue by idanpt** [MichalSzorad/react-social-login-buttons#26]
in particular: when clicked on a link on FB app, which is opened in the FB browser.
maybe connected to 
`https://stackoverflow.com/questions/37269888/facebook-login-is-not-working-in-app-browser-for-ios` ?

**Comment by Braythor** [comment]
Im trying to understand this, you logged in using the button and Facebook accepted the login. Everything is normal, except when clicking a link in the app which should open the Facebook browser in-app it didn't. It sounds like a Facebook bug.

**Comment by idanpt** [comment]
sorry!! i posted this issue to the wrong repo. (obviously meant
react-social-login).
I'm closing it.

‫בתאריך יום ג׳, 1 בינו׳ 2019 ב-8:01 מאת ‪Braythor‬‏ <‪
notifications@github.com‬‏>:‬
