### ISSUE TITLE
Twitter uses old icon

### ISSUE THREAD

**Issue by GitHubGreg** [MichalSzorad/react-social-login-buttons#28]
Great package, thanks! Just mentioning that the Twitter logo used is the old one (beak pointing right). Your screenshot shows the new one (beak pointing up-right) but that isn't what outputs when I use this package. Thanks :-)

**Comment by MichalSzorad** [comment]
Hi @GitHubGreg, thanks for the issue! I will update the twitter icon and make a new release as soon as I can.

**Comment by MichalSzorad** [comment]
Hi @GitHubGreg, I have just published a new version of react-social-login-buttons, which should contain the new Twitter Logo.

Thanks for contributing!

**Comment by GitHubGreg** [comment]
Thanks for the quick turnaround!
