### ISSUE TITLE
Icons aren't showing up

### ISSUE THREAD

**Issue by bradeac** [MichalSzorad/react-social-login-buttons#3]
Hi,

A bit of a newbie here, so probably I'm missing something which would be extremely obvious to someone else.

I'm using your social buttons together with the 'react-social-login' package.

The code looks something like this (just the relevant bits):

```
import { OldSocialLogin as SocialLogin } from 'react-social-login';
import GoogleLoginButton from 'react-social-login-buttons/lib/buttons/GoogleLoginButton';

class Login extends React.Component {
    defaults = {
        text: 'Login with Google',
        icon: 'google',
        iconFormat: name => `fa fa-${name}`,
        style: {background: "#3b5998"},
        activeStyle: {background: "#293e69"}
    };

    responseGoogle = (e) => {
        console.log(e);
    }

    render() {
        return (
            <div>
                <SocialLogin
                    defaults={this.defaults}
                    provider='google'
                    appId="app_id_goes_here :)"
                    callback={this.responseGoogle}
                >
                <GoogleLoginButton>Login with Google</GoogleLoginButton>
                </SocialLogin>
            </div>
        );
    }
}
```
I also tried without 'defaults'. No matter what I do, the icons do not appear, even though the rest of the button looks as expected.

I'll appreciate if you can help me a bit, as I said, a bit of a newbie here.

Thanks.

**Comment by MichalSzorad** [comment]
Hi @bradeac thanks for the feedback. I will take a look at the problem.

**Comment by MichalSzorad** [comment]
@bradeac Are you trying to change the text and keep the icon? If yes, try using 
```<GoogleLoginButton  text="Login with Google" />``` 
instead of 
```<GoogleLoginButton>Login with Google</GoogleLoginButton> ```

I will have to work on the docs. [The current docs ](https://www.npmjs.com/package/react-social-login-buttons) are not easy to read and the API could be better for sure.

Please let me know if the issue persists.

**Comment by MichalSzorad** [comment]
Btw you are passing `defaults` to the `SocialLogin` component (not our component). `defaults` also works only on the `SocialLoginButtonProvider`

**Comment by bradeac** [comment]
Hi,

Thanks for the replies. I've changed some stuff and now it looks like this:
```
import { OldSocialLogin as SocialLogin } from 'react-social-login';
import { GoogleLoginButton, FacebookLoginButton } from 'react-social-login-buttons';

class Login extends React.Component {
    render() {
        return (
                <div>
                    <SocialLogin
                           provider='google'
                           appId="app_id_here"
                           callback={this.response}
                    >
                        <GoogleLoginButton>Login with Google</GoogleLoginButton>
                    </SocialLogin>
               </div>
        );
}
```

The button still has no icon. I've also tried using 'defaults' (to the right component this time) and still no icon.

Thanks.

**Comment by bradeac** [comment]
Hi.

Found the issue.
I was using it this way:
```
<GoogleLoginButton>Login with Google</GoogleLoginButton>
```

It appears that the correct way is this:
```
<GoogleLoginButton text="Login with Google" />
```

This way the icons are being visible. Although the correct usage appeared in the documentation, I wasn't aware that this small change would result in a different behaviour.

Keep up the good work 👍
