### ISSUE TITLE
LoginButton not tab-able 

### ISSUE THREAD

**Issue by flolege** [MichalSzorad/react-social-login-buttons#30]
I use the Login Buttons in a react-bootstrap Modal. Inside the Modal, I can circle-tab through all elements like Buttons or Input fields, but the Login Buttons are not tab-able, meaning they do not get selected when using TAB. 

I tried playing around with autoFocus or setting tabindex=1, but it doesn't work. Any suggestions how to solve that issue?

**Comment by MichalSzorad** [comment]
@flolege could you try the latest version - 3.0.0?

**Comment by flolege** [comment]
Works!! Many thanks, great!
