### ISSUE TITLE
Cannot find name 'ComponentClass' types error

### ISSUE THREAD

**Issue by marcoboncoraglio** [MichalSzorad/react-social-login-buttons#33]
After installing from npm and implementing I get:

TypeScript error in [...]/react-social-login-buttons/src/types.d.ts(48,72):
Cannot find name 'ComponentClass'.  TS2304

I believe this issue has already been fixed in the bugfix/types branch, but somehow not yet merged to production.

**Comment by MichalSzorad** [comment]
@marcoboncoraglio I am not able to reproduce this issue. What version of react-social-login-buttons and TypeScript are you using?
