### ISSUE TITLE
Inherit icon color

### ISSUE THREAD

**Issue by remorses** [MichalSzorad/react-social-login-buttons#35]
Isons have an hard coded color of `#fff`, we could remove the `fill` attribute  from svg icons to use the color added with the `style` tag, an example icon that is hard coded as white:

https://github.com/MichalSzorad/react-social-login-buttons/blob/5217e4871eeffc9537b4d7d8f0f249496d56f715/src/buttons/FacebookLoginButton.js#L20

**Comment by MichalSzorad** [comment]
Hello, thank you for the issue!

I have just released v3.1.0 where you can specify `iconColor` on a SocialLoginButton. Let me know if that does not help.

Cheers!
