### ISSUE TITLE
Custom button: icons doesn't load

### ISSUE THREAD

**Issue by louislefebvre** [MichalSzorad/react-social-login-buttons#38]
Hello :)
I am writing this issue because I am unable to get a custom button with the button displaying an icon.

![image](https://user-images.githubusercontent.com/9850177/73864616-4885ef80-4842-11ea-8e45-5bf534cdf2d8.png)
![image](https://user-images.githubusercontent.com/9850177/73863650-afa2a480-4840-11ea-8e25-3934bd09a0f7.png)

And if I test with createSvgIcon, I get the following error:
![image](https://user-images.githubusercontent.com/9850177/73864553-2b512100-4842-11ea-8e00-2fc2e55dd67f.png)
![image](https://user-images.githubusercontent.com/9850177/73864509-15dbf700-4842-11ea-9448-96f265914ecb.png)

Is it on my side? Or is there something wrong with the dependency?
Thanks!

**Comment by MichalSzorad** [comment]
Hello, thank you for the issue!

I have just released v3.1.0 give it a try and let me know if that helps.

Cheers!

**Comment by Shoreasg** [comment]
Hey there, seem like this issue is back again.
