### ISSUE TITLE
v3.1.2: Google Login Button

### ISSUE THREAD

**Issue by niall-byrne** [MichalSzorad/react-social-login-buttons#49]
First thanks for your hard work in providing this handy package,

I noticed when I upgraded to 3.1.2 that the Google button was not being rendered in the red styling that you created.  It is instead falling back to the default style.

I tested this on both node 12 and 14, as I wasn't sure what the root cause was, but this is what I'm seeing:

## Version 3.1.2, delete node_modules, re-install
![image](https://user-images.githubusercontent.com/9848926/104481783-2dfce000-5594-11eb-9d47-e9c3c4e0c42a.png)

## Downgrade to Version 3.1.0, delete node_modules, re-install
![image](https://user-images.githubusercontent.com/9848926/104483127-c6479480-5595-11eb-863a-79798909b9e3.png)

It's possible there is some other factor at play, but I just wanted to validate that the new release has the correct content.

**Comment by niall-byrne** [comment]
I see now this is intentional from looking at the commit history.
It may make sense to clean up the documentation and code example in light of your planned changes.

**Comment by MichalSzorad** [comment]
Yes, that has been intentional. I will need to update the docs and the image. Thank you for pointing out this issue.
