### ISSUE TITLE
Change text from Login to Log in

### ISSUE THREAD

**Issue by multiwebinc** [MichalSzorad/react-social-login-buttons#52]
Call me a grammar Nazi, but the default texts should be "Log in", not "Login".

> Login, spelled as one word, is only a noun or an adjective. For example, the information you use to sign into your email is your login (noun), and the page where you sign in is the login page (adjective). Log in is two words when it functions as a verb. For example, you log in with your login information.

-- https://grammarist.com/spelling/log-in-login/

**Comment by MichalSzorad** [comment]
This should be resolved in version 3.1.4, thank you!
