### ISSUE TITLE
Discord login button

### ISSUE THREAD

**Issue by roadsidev** [MichalSzorad/react-social-login-buttons#55]
Hey!
Love your project. 

Lately been using the Discord auth method and I would love to keep using your package for this!

Hope you can add it sometime in the future. 

Cheers

**Comment by roadsidev** [comment]
I made a pull request #56 in case you want to merge it

**Comment by MichalSzorad** [comment]
Thank you @roadsidev. This should be now available in the version 3.4.0.

Cheers
