### ISSUE TITLE
Does not work with Expo

### ISSUE THREAD

**Issue by smodekurti** [MichalSzorad/react-social-login-buttons#6]
I am not able to make this component work with Expo. I get an error message 

Unable to resolve module `!!../../../node_modules/css-loader/index.js!./social-login-font.css` from /Users/xxx/node_modules/react-social-login-buttons/lib/fontello-social/css/social-login-font-css.js` Module does not exist in the module map

**Comment by MichalSzorad** [comment]
Hello @smodekurti,

thanks for the feedback. I will take a look at this issue later today.

**Comment by MichalSzorad** [comment]
@smodekurti, unfortunately, we do not support react-native yet.
