### ISSUE TITLE
Form is posting on button click on react - how to disable

### ISSUE THREAD

**Issue by leopucci** [MichalSzorad/react-social-login-buttons#69]
Hi, thanks for your job on this component. 
I am struggling with a feature, when I click on this button, it submits the form. other react buttons that I use they don´t submit, so you can use onClick function to make it work.
I know that it needs a preventDefault() somewhere, but I lack of react knowledge to know where. 
If someone knows how to prevent the submit on react, would help me a lot. 
I am creating this issue because this can help other users also (I guess :) )
Thanks
Pucci

**Comment by leopucci** [comment]
I discovered that is because of the type. 
By default, button elements are of the type "submit" which causes them to submit their enclosing form element (if any). 

Changing the type to "button" prevents that. 
All other buttons that I use have this `type="button"`

**Comment by leopucci** [comment]
Somebody already stumbled on this https://github.com/MichalSzorad/react-social-login-buttons/pull/58

**Comment by leopucci** [comment]
@MichalSzorad could you merge this pull request?

**Comment by MichalSzorad** [comment]
@leopucci merged and deployed, please try version 3.5.1

**Comment by MichalSzorad** [comment]
@leopucci thank you for creating the issue and for contributing!

**Comment by leopucci** [comment]
Thank you for your help, already tested and it worked properly. have a nice day!
