### ISSUE TITLE
Uncaught TypeError: Cannot read property 'preventDefault' of undefined

### ISSUE THREAD

**Issue by leopucci** [MichalSzorad/react-social-login-buttons#70]
I´m having some trouble using this button with https://github.com/A-Tokyo/react-apple-signin-auth
![image](https://user-images.githubusercontent.com/38509299/130324584-df9c6f1d-7caf-4dff-8cfc-6d1e7df8aade.png)

The module is trying to use preventDefault() from the form post but there is no post to be prevented. Maybe it is because of that. 
![image](https://user-images.githubusercontent.com/38509299/130324874-6460cdd0-1155-4acc-bd44-0573108615bf.png)

The strange thing is that I use `react-social-login-buttons` with https://www.npmjs.com/package/react-google-login and works properly. 

I 've opened an issue on the `react-apple-signin-auth` module, because I think that maybe there is no need to preventDefault on the module. But I don´t know why this module does not play well with it. 
https://github.com/A-Tokyo/react-apple-signin-auth/issues/61

The strange is that if I use a single <button> it works properly.
![image](https://user-images.githubusercontent.com/38509299/130325178-15811371-63d3-485e-b84b-86283baaa0e2.png)

But if I use Apple button (or others from the module) it does not work. 
![image](https://user-images.githubusercontent.com/38509299/130325213-096a4c20-a29a-48bd-baba-ae1195610002.png)

Any ideas?
Thanks
Pucci

**Comment by leopucci** [comment]
This error is frequently seen when creating a function inside a React.js component. It happens because of an incorrect binding of this. Sometimes the scope is not setup correctly which causes the event object to be undefined.

So, how can you fix the cannout read property preventDefault of undefined error? This can be fixed by using the following methods

Not executing the function in the callback handler (most likely culprit)
Binding the scope correctly with an arrow function
Using JavaScript’s .bind() to set the correct scope.

**Comment by leopucci** [comment]
@MichalSzorad I tried to compile/fork to test and I was not able to test on windows. 
I think that this function is not giving the parameter ahead, so that´s why I am having trouble with this module. 
![image](https://user-images.githubusercontent.com/38509299/130333718-c94b7f25-7800-4237-9995-7a6c126ee332.png)
![image](https://user-images.githubusercontent.com/38509299/130333729-893e6950-25f9-41e9-848d-878cb2f6c706.png)

**PULL REQUEST** >> https://github.com/MichalSzorad/react-social-login-buttons/pull/71
**BUILD AND TEST - NOT DONE:**
I tryed the usual npm install myGitHub/package#masterOrdev
For some reason the module does not install properly. 
npm install michalszorad/react-social-login-buttons#develop
![image](https://user-images.githubusercontent.com/38509299/130333672-534414ff-5287-4c6e-9bb8-e2015b706442.png)
I am trying to build and test so the pull request could be properly sent but I couldn´t so I didn´t test it ok?
Do you have some instructions so I could be able to build/compile this module?
Thanks
Pucci

**Comment by MichalSzorad** [comment]
@leopucci please see version 3.6.0. Thanks for the contribution
