### ISSUE TITLE
Not working with the latest react version

### ISSUE THREAD

**Issue by bobthebuilder1997** [MichalSzorad/react-social-login-buttons#87]
Cannot install the extension. It's peerDependency ia only react versions up to 17.x.x

npm i react-social-login-buttons
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: p2@1.0.0
npm ERR! Found: react@18.2.0
npm ERR! node_modules/react
npm ERR!   dev react@"^18.2.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^15.0.0 || ^16.0.0 || ^17.x" from react-social-login-buttons@3.6.0
npm ERR! node_modules/react-social-login-buttons
npm ERR!   react-social-login-buttons@"*" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.

**Comment by michalszorad** [comment]
@bobthebuilder1997 please try version 3.6.1
