### ISSUE TITLE
Demo is giving an error of "No valid scopes requested"

### ISSUE THREAD

**Issue by RiddhiBelani** [MichalSzorad/react-social-login-buttons#96]
I've ran live demo which is given [here](https://www.npmjs.com/package/reactjs-social-login/v/2.6.1) its giving me an error that `{"error_type": "OAuthException", "code": 400, "error_message": "No valid scopes requested"}`

```
"react": "^18.2.0",
"reactjs-social-login": "^2.6.1",
```

Any help is appriciated. 
Thank you.

**Comment by michalszorad** [comment]
@RiddhiBelani I think this is a wrong repo. This repo is for `react-social-login-buttons` and not for `reactjs-social-login`.

I'm closing this issue. If you think this is still relevant, please let me know. Cheers!

**Comment by RiddhiBelani** [comment]
Hey Michal,

Thank you for looking into the social login buttons issue. I was facing an
issue so I just integrated an alternative to that library. Will surely let
you know if I'll use this in the future.

Thanks & Regards,
Riddhi Belani.
